config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'movies#index'
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :movies do
    post '/upvote', to: 'movies#upvote', as: :like, on: :member
    post '/downvote', to: 'movies#downvote', as: :hate, on: :member
    get '/user_movies', to: 'movies#user_movies', on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
# frozen_string_literal: true

class Movie < ApplicationRecord
  belongs_to :user
  has_many :votes

  # Validations
  validates :title, presence: true
  validates :user_name, presence: true

  # Scopes

  scope :likes, ->(movie_id) { Vote.where(like: true, movie: movie_id).count }
  scope :hates, ->(movie_id) { Vote.where(hate: true, movie: movie_id).count }

  def day_ago_created
    "#{(DateTime.now - created_at.to_date).to_i} days ago"
  end

  def liked?(user_id)
    return unless user_id

    !!votes.find { |vote| vote.user_id == user_id && vote.like }
  end

  def hated?(user_id)
    return unless user_id

    !!votes.find { |vote| vote.user_id == user_id && vote.hate }
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  # Validation
  validates :user_id, uniqueness: { scope: :movie_id }

  def increase_movie_like_count
    movie.increment!(:like_count, 1)
  end

  def decrease_movie_like_count
    movie.decrement!(:like_count, 1)
  end

  def increase_movie_hate_count
    movie.increment!(:hate_count, 1)
  end

  def decrease_movie_hate_count
    movie.decrement!(:hate_count, 1)
  end

  private

  def movie
    Movie.find(movie_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
# frozen_string_literal: true

class MoviesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create update destroy upvote downvote user_movies]
  before_action :set_movie, only: %i[show edit update destroy upvote downvote]
  before_action :set_filter, only: %i[index]

  # GET /movies or /movies.json
  def index
    @movies = Movie.includes(:votes).all.order(@filter)
  end

  def show; end

  def new
    @movie = Movie.new(user_name: current_user.full_name)
  end

  def edit; end

  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: 'Movie was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: 'Movie was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
    end
  end

  def upvote
    @vote = Vote.find_or_initialize_by(movie_id: @movie.id, user_id: params[:user_id])
    @vote.transaction do
      @vote.decrease_movie_hate_count if @vote.hate
      @vote.increase_movie_like_count
      @vote.like = true
      @vote.hate = false
      respond_to do |format|
        if @vote.save
          format.html { redirect_to movies_url }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  end

  def downvote
    @vote = Vote.find_or_initialize_by(movie_id: @movie.id, user_id: params[:user_id])
    @vote.transaction do
      @vote.decrease_movie_like_count if @vote.like
      @vote.increase_movie_hate_count
      @vote.like = false
      @vote.hate = true
      respond_to do |format|
        if @vote.save
          format.html { redirect_to movies_url }
        else
          format.html { render :new, status: :unprocessable_entity }
        end
      end
    end
  end

  def user_movies
    @movies = Movie.includes(:votes).where(user_id: params[:user_id]).order(@filter)
  end

  private

  def set_filter
    @filter = case params[:filter]
              when 'like'
                { like_count: :desc }
              when 'hate'
                { hate_count: :desc }
              else
                { created_at: :desc }
              end
  end

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :description, :user_name, :likes, :hates, :user_id, :user_name)
  end
end

app/controllers/registrations_controller.rb
# frozen_string_literal: true

class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, only: %i[create update]

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name email password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MovieRama</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <%= link_to root_path do %>
        <h1>Movies</h1>
      <% end %>
    </div>
    <div class="col-sm-6">
      <% if user_signed_in? %>
        Welcome back <u><%= current_user.full_name %></u>&nbsp; | <%= link_to 'Add new movie', new_movie_path %>
        | <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Login', user_session_path %> | <%= link_to 'Sign up', new_user_registration_path %>
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value:  current_user.id %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_name, value: current_user.full_name %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/movies/_movies_list.html.erb
<% movies.each do |movie| %>
  <div class="card">
    <div class="card-header">
      <h5 class="card-title"><%= movie.title %></h5>
    </div>
    <div class="card-body">
      <h6 class="card-subtitle mb-2 text-muted">Posted By:&nbsp;&nbsp
        <% if current_user&.id == movie.user_id %>
          <%= link_to "Me", user_movies_movies_path(user_id: current_user&.id) %>&nbsp;
        <% else %>
          <%= link_to movie.user_name, user_movies_movies_path(user_id: movie.user_id) %>&nbsp;
        <% end %>
        &nbsp <%= movie.day_ago_created %></h6>
      <p class="card-text"><%= movie.description %></p>
      <div class="row">
        <div class="col-sm-6">
          <%= movie.like_count %> likes | <%= movie.hate_count %> hates
        </div>
        <div class="col-sm-6">
          <% unless current_user&.id == movie.user_id %>
            <% if movie.liked?(current_user&.id) %>
              You like this movie |
            <% else %>
              <%= link_to "Like", like_movie_path(movie.id, user_id: current_user&.id), method: :post %> |
            <% end %>
            <% if movie.hated?(current_user&.id) %>
              | You hate this movie
            <% else %>
              <%= link_to "Hate", hate_movie_path(movie.id, user_id: current_user&.id), method: :post %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <br>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>
<nav class="navbar navbar-light bg-light">
  <div> Sort By  <%= link_to "Like", movies_path(filter: 'like') %>
    | <%= link_to "Hate", movies_path(filter: 'hate') %>
    | <%= link_to "Date", movies_path(filter: 'date') %></div>
</nav>

<%= render 'movies/movies_list', movies: @movies %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>


<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @movie.title %></h5>
    <p class="card-text"><%= @movie.description %></p>
  </div>
</div>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/movies/user_movies.html.erb
<nav class="navbar navbar-light bg-light">
  <div> Sort By  <%= link_to "Like", user_movies_movies_path(user_id: @movies.first.user_id, filter: 'like') %>
    | <%= link_to "Hate", user_movies_movies_path(user_id: @movies.first.user_id, filter: 'hate') %>
    | <%= link_to "Date", user_movies_movies_path(user_id: @movies.first.user_id, filter: 'date') %></div>
</nav>

<%= render 'movies/movies_list', movies: @movies %>